// Code generated by frontend/scripts/gen-theme-fonts.mjs — DO NOT EDIT.
// Source of truth: frontend/src/styles/themeFonts.source.json.
// Regenerate: npm run gen:fonts (this file).

/** The whitelist of --font-* token names a theme bundle's optional `fonts`
 * map may re-value. Client + mock validation whitelist. */
export const THEME_FONT_TOKENS: readonly string[] = [
  "--font-sans",
  "--font-title",
];

/** One safe, curated font-family stack. `stack` is the ONLY string a bundle
 * may store for a font token; `label` is the friendly name shown in the
 * theme editor's font dropdown. The value set (the `stack`s) is a CLOSED
 * allowlist — never an arbitrary string. */
export interface SafeFontFamily {
  readonly id: string;
  readonly label: string;
  readonly stack: string;
}

export const SAFE_FONT_FAMILIES: readonly SafeFontFamily[] = [
  { id: "system", label: "System UI", stack: "system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif" },
  { id: "grotesk", label: "Schibsted Grotesk", stack: "\"Schibsted Grotesk\", \"Noto Sans TC\", system-ui, sans-serif" },
  { id: "noto-sans", label: "Noto Sans", stack: "\"Noto Sans TC\", \"Noto Sans\", system-ui, sans-serif" },
  { id: "serif", label: "Serif", stack: "\"Noto Serif TC\", Georgia, \"Times New Roman\", serif" },
  { id: "kai", label: "標楷體", stack: "\"BiauKai\", \"DFKai-SB\", \"Kaiti TC\", \"Kaiti\", KaiTi, serif" },
  { id: "heiti", label: "黑體", stack: "\"PingFang TC\", \"Microsoft JhengHei\", \"Heiti TC\", sans-serif" },
  { id: "songti", label: "宋體", stack: "\"Songti TC\", \"Songti SC\", SimSun, serif" },
  { id: "yuanti", label: "圓體", stack: "\"Yuanti TC\", \"Yuanti SC\", sans-serif" },
  { id: "mono", label: "Monospace", stack: "ui-monospace, \"SF Mono\", Menlo, Consolas, monospace" },
];
