// Command ocupdaterd is the officraft release/update server.
//
// What it is for: the publisher (owner-side) pushes released server binaries
// here with a PUBLISH TOKEN (cli/ocrelease is the publishing client); invited
// users install with an INVITE CODE one-liner (GET /install.sh?code=...), and
// their installed server later asks this daemon for updates with the same
// invite code.
//
// Channels (owner decided 2026-07-14): every publish lands in BETA; POST
// /api/promote stamps a version GA. GET /api/latest?channel=ga|beta answers
// per channel, DEFAULTING TO GA — clients that say nothing get the stable
// channel. See store.go (ga_at) and server.go for the exact semantics.
//
// Management PORTAL (portal.go + portal.html): a browser UI at /portal/ over
// versions/promote/invites plus the downstream FLEET MONITOR — every invite
// is one downstream OC, and /api/latest doubles as its heartbeat (check time
// + self-reported current_version/current_sha land on the invite row). Auth
// is the ocserverd first-run pattern: serve prints a one-shot claim URL while
// no portal password is set; after the claim, password login mints a hashed
// session token. The local CLI subcommands below remain the shell-access
// management face — the portal is the remote-operator face of the same store.
//
// Honesty notes:
//   - the deployment-location design card is still awaiting the owner.
//   - the version-format card is CLOSED (owner decided 2026-07-13): versions
//     are date-form vYYMMDD-NNNN, generated by the server at publish when the
//     client sends none (see version.go).
//   - invite-code semantics are CLOSED (owner): per-person, long-lived,
//     revocable, doubling as the update-check credential.
//
// Naming (root CLAUDE.md §10): folder server/ocupdaterd/ = module ocupdaterd
// = binary ocupdaterd; committed prebuilt lives at bin/ocupdaterd (CI step 1
// parity gate). Deliberately OUTSIDE spec/openapi.json and conformance/ —
// those freeze the ocserverd wire, and this is a different daemon.
package main

import (
	"fmt"
	"io"
	"os"
)

// subcommands is the CLI surface. Kept as data so the usage text and the
// dispatch stay in one place (mirrors server/ocserverd/main.go).
var subcommands = []struct{ name, help string }{
	{"serve", "run the update server (default): read ./oc-updater.toml, bind 127.0.0.1:[server].port"},
	{"mint-publish-token", "mint a publish credential (prints the token ONCE; only its hash is stored)"},
	{"list-publish-tokens", "list publish tokens (id, name, created, revoked)"},
	{"revoke-publish-token", "revoke a publish token by id: revoke-publish-token <id>"},
	{"mint-invite", "mint an invite code for one person: mint-invite --name <who>"},
	{"revoke-invite", "revoke an invite code by id: revoke-invite <id>"},
	{"list-invites", "list invite codes (id, name, created, revoked)"},
	{"list-versions", "list published versions (newest first, with their beta/GA channel)"},
}

func usage(out io.Writer) {
	fmt.Fprintln(out, "usage: ocupdaterd [subcommand] [flags]")
	fmt.Fprintln(out, "  officraft release/update server (beta/GA dual channel: publish→beta, promote→GA).")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "subcommands:")
	for _, s := range subcommands {
		fmt.Fprintf(out, "  %-21s %s\n", s.name, s.help)
	}
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "config: ./oc-updater.toml (or $OC_UPDATER_CONFIG) — [server].port (default 8790),")
	fmt.Fprintln(out, "        [storage].data_dir (default ~/.ocupdaterd). Management subcommands operate")
	fmt.Fprintln(out, "        directly on the local database (no HTTP admin surface in M1).")
}

// realMain is the testable entrypoint: argv WITHOUT the program name, an env
// accessor, and the output sink. Returns the process exit code (mirrors
// server/ocserverd/main.go realMain).
func realMain(argv []string, env func(string) string, out io.Writer) int {
	// Default subcommand is serve (the zero-argument canonical start), except
	// the help flags, which route to usage (exit 0).
	cmd, rest := "serve", argv
	if len(argv) > 0 {
		switch {
		case argv[0] == "-h" || argv[0] == "--help":
			cmd, rest = "help", nil
		case argv[0] != "" && argv[0][0] != '-':
			cmd, rest = argv[0], argv[1:]
		}
	}

	switch cmd {
	case "serve":
		if len(rest) != 0 {
			fmt.Fprintf(out, "[ocupdaterd] serve takes no flags (unknown: %q)\n\n", rest[0])
			usage(out)
			return 2
		}
		return cmdServe(env, out)

	case "mint-publish-token":
		name, bad := parseNameFlag(rest, "publisher", out)
		if bad {
			return 2
		}
		return cmdMint(env, kindPublish, name, out)

	case "list-publish-tokens":
		if len(rest) != 0 {
			fmt.Fprintln(out, "[ocupdaterd] list-publish-tokens takes no arguments")
			return 2
		}
		return cmdListCredentials(env, kindPublish, out)

	case "revoke-publish-token":
		if len(rest) != 1 {
			fmt.Fprintln(out, "[ocupdaterd] usage: revoke-publish-token <id>   (find the id with list-publish-tokens)")
			return 2
		}
		return cmdRevokeCredential(env, kindPublish, rest[0], out)

	case "mint-invite":
		name, bad := parseNameFlag(rest, "", out)
		if bad {
			return 2
		}
		if name == "" {
			fmt.Fprintln(out, "[ocupdaterd] mint-invite needs --name <who> (one invite per person)")
			return 2
		}
		return cmdMint(env, kindInvite, name, out)

	case "revoke-invite":
		if len(rest) != 1 {
			fmt.Fprintln(out, "[ocupdaterd] usage: revoke-invite <id>   (find the id with list-invites)")
			return 2
		}
		return cmdRevokeCredential(env, kindInvite, rest[0], out)

	case "list-invites":
		if len(rest) != 0 {
			fmt.Fprintln(out, "[ocupdaterd] list-invites takes no arguments")
			return 2
		}
		return cmdListCredentials(env, kindInvite, out)

	case "list-versions":
		if len(rest) != 0 {
			fmt.Fprintln(out, "[ocupdaterd] list-versions takes no arguments")
			return 2
		}
		return cmdListVersions(env, out)

	case "-h", "--help", "help":
		usage(out)
		return 0

	default:
		fmt.Fprintf(out, "[ocupdaterd] unknown subcommand %q\n\n", cmd)
		usage(out)
		return 2
	}
}

// parseNameFlag parses the one-flag surface `--name <who>` by hand (the stdlib
// FlagSet would print its own usage on error, diverging from usage()).
// Returns (name, bad-args).
func parseNameFlag(args []string, def string, out io.Writer) (string, bool) {
	name := def
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--name", "-name":
			if i+1 >= len(args) {
				fmt.Fprintln(out, "[ocupdaterd] --name needs a value")
				return "", true
			}
			i++
			name = args[i]
		default:
			fmt.Fprintf(out, "[ocupdaterd] unknown flag %q\n\n", args[i])
			usage(out)
			return "", true
		}
	}
	return name, false
}

func main() {
	os.Exit(realMain(os.Args[1:], os.Getenv, os.Stdout))
}
