-- +goose Up
-- T-14 項目 7 — the SECOND intent, split out of desired_state.
--
-- desired_state carried two different owner intents at once: HOW HARD this
-- member is being taken down (停止 / 加速停止 / 強制停止) and WHETHER it should
-- be running afterwards. One column cannot hold both, so a 重啟 verb arriving
-- on a member the owner had already stopped had nowhere to record "and bring it
-- back up" — the server either refused (refocus: 409) or stored the new
-- machine / model and did nothing (relocate / 換 model: a clean 200).
--
--   0  nothing is waiting to come back up (every pre-column row starts here).
--   1  the owner's LAST action on this member was a 重啟 intent while it was on
--      its way down: honour the stronger stop, then bring it up.
--
-- Owner 2026-08-30 (rc-bc1b029a3aa2): 「一個重啟的 intention 遇上一個更強硬的
-- 下線規則 他的方式是沿用強硬下線規則 但是附加上線規則」.
--
-- 「要不要起來」 is LAST-WRITER-WINS (a down verb clears this, a 重啟 verb sets
-- it); 「下線用多強」 stays a RATCHET on the existing ladder. Splitting them is
-- the whole change — the ladder is untouched.
--
-- Deliberately NOT on the wire (no DTO field, no spec change), like
-- session_boot_ts and handover_noticed_ts: it is consumed by the reconcile tick
-- at the converged-offline edge, and what the cockpit shows is the receipt the
-- verb already stamps in last_op_reason.
-- NUMBER: 00070, taken at land time. This file was authored as 00066 — free on
-- main then (main's last was 00065), but main is not the denominator: a sweep of
-- the remote branches found 00066_lore.sql on six t-33/* branches, and 00067 /
-- 00068 taken on t-48/spec-chat-api and t-33/lore-tab-ui. main has since reached
-- 00069 (00069_account_spend.sql), so this file was renumbered to 00070 before
-- landing and its predecessor in the merged ladder is 00069, NOT 00069's
-- neighbour by arithmetic — main's numbering has gaps (64, 66, 67, 68 are all
-- absent), so "this number minus one" is not "the stage before this one".
--
-- Two sources have to be swept, not one: the .sql files under migrations/ AND
-- the Go migrations registered with goose.AddNamedMigrationContext, which live
-- beside the package as server/ocserverd/migration_000NN_*.go (00054, 00059) and
-- are invisible to a listing of migrations/. See
-- migration_version_scan_t49e7_test.go.
--
-- A collision cannot ship silently — goose panics on a duplicate version
-- (pressly/goose migrate.go: "goose: duplicate version %v detected") and this
-- tree reaches it through goose.Up in migrate.go — but it panics at the worst
-- place: station start-up, on the operator's machine.
--
-- Renumbering this file touches THREE places:
--   1. this filename;
--   2. server/ocserverd/dal.go — the Member.RestartAfterStop doc comment;
--   3. server/ocserverd/dal_member_patch.go — the mfRestartAfterStop comment.
-- No test pins this version or its PRIOR version: nothing in *_test.go calls
-- DownTo/UpTo near this file's number, and the named-constant pattern that
-- carries that trap (migration00065Version / migration00065PriorVersion in
-- api_replycards_multiselect_t40_test.go, migration00061* in
-- migration_00061_drop_non_general_lessons_test.go) is NOT used here. If a
-- rollback test is added later it MUST take both numbers from named constants —
-- changing only the migration's own number and leaving the prior one behind
-- leaves the test green while it stops testing this migration's rollback.
ALTER TABLE member ADD COLUMN restart_after_stop INTEGER NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE member DROP COLUMN restart_after_stop;
