// Code generated by frontend/scripts/gen-theme-fonts.mjs — DO NOT EDIT.
// Source of truth: frontend/src/styles/themeFonts.source.json.
// Regenerate: npm run gen:fonts (server/ocserverd/theme_fonts_gen.go).

package main

// themeFontTokens is the whitelist of --font-* token names a theme bundle's
// optional `fonts` map may re-value (theme_bundle.go / font_bundle.go
// validation). Extracted from frontend/src/styles/themeFonts.source.json.
var themeFontTokens = map[string]bool{
	"--font-sans":  true,
	"--font-title": true,
}

// themeFontStacks is the CLOSED allowlist of font-family stack strings a font
// value may be. A value outside this set is a 422 — never an arbitrary string.
var themeFontStacks = map[string]bool{
	"\"Noto Sans TC\", \"Noto Sans\", system-ui, sans-serif":         true,
	"\"Noto Serif TC\", Georgia, \"Times New Roman\", serif":         true,
	"\"Schibsted Grotesk\", \"Noto Sans TC\", system-ui, sans-serif": true,
	"system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif":     true,
	"ui-monospace, \"SF Mono\", Menlo, Consolas, monospace":          true,
}
